### ISSUE TITLE
Client bastion needs to properly forward registration requests to the server to clear the miss cache.

### ISSUE THREAD

**Issue by Kapps** [Kapps/funcie#2]
Currently there's a delay of up to a minute if an application is cached as being not found. A register should clear that, but it doesn't because the register doesn't get forwarded to the server bastion. It should do so.

**Comment by ogi-resolver** [comment]
For now, the cache is removed.

**Comment by Kapps** [comment]
Now the client bastion unsubscribes when the application isn't running, preventing the round trip.
